### ISSUE TITLE
Make Address Generic and add variants

### ISSUE THREAD

**Issue by MitchTurner** [free-honey/naumachia#9]
Right now it's just a `String` under the hood and there is no difference between wallet addresses, policies, and script addresses.

At the very least, we should reevaluate this.

**Comment by Ch1n3du** [comment]
I'd like to try this, do have anything in mind? I was thinking of a simple `enum`.

**Comment by MitchTurner** [comment]
I haven't spent a long time thinking about this, tbh. I just don't like `String`s for things that could be typed.

An enum might be all we need if we are okay with using a `String` under the hood. But what I meant by "generic" was the Address type could be chosen by the implementer:

```
pub enum Address<T> {
    Wallet(T),
    Validator(T),
    ...
}
```
This way we can use a `String` in the tests (like we're currently using) and something a little more robust for the actual production code.

I'm not sure what problem this solves yet though. So this story isn't high priority.

**Comment by MitchTurner** [comment]
I think I'm actually gonna knock this out as I do the BlockFrost client stuff. I'll need a better concept of Addresses in order to working.

**Comment by MitchTurner** [comment]
Woof. Okay, so I went down the generic `Address` rabbit hole. I thought it was going really well. I was even feeling proud of my generic-foo and tuning the assoc types in the right places... and then I ran `cargo test` and there was an explosion of `Address` generics everywhere. 

This was actually expected--at least it's very common in these start of designs--but it actually ruins the ergonomics of the library. I don't want the consumer to need to worry about all the `Address` generics. So I ended rolling back the work and I'm gonna prolly go a different route.

I really don't want to push the logic of managing the relationship of base addr, and staking addr, and payment addr, and everything into the domain of Naumachia. I liked the generic approach because you can have each type deal with the relationships and conversion, and the tests can just use raw, readable strings.

Not happy about this. Gonna keep hitting my head on the wall.

**Comment by Ch1n3du** [comment]
It's tricky but you'll figure it out

**Comment by MitchTurner** [comment]
We've ended up just depending on the Pallas Addresses. It just makes everything so much easier.
